### ISSUE TITLE
Slower flant5-large using CTanslate then the original

### ISSUE THREAD

**Issue by AparnaAgrawal02** [OpenNMT/CTranslate2#1319]
https://drive.google.com/file/d/1MjA_jpaZS89pCvnemz_VaB_LUKmXc-CX/view?usp=sharing 
This is the code. 
I am trying to compare the inference time of the original flant5 and using ctranslate2,
It seems that ctranslate2 is way slow. 
for original hugging face.
seq_len:  32 time:  3.6980602312088013 
seq_len:  128 time:  4.272962679862976
with  ctranslate2.
seq_len:  32 time:  5.161652681827545  
seq_len:  128 time:  48.885592801570894
I am running both on the CPU.

**Comment by guillaumekln** [comment]
The 2 runs are using different parameters.

You should at least set these parameters for CTranslate2:

* `beam_size=1`
* `max_length=20`

For CPU inference you should also make sure that the same number of threads is used. You can set these lines at the top of your script:

```python
import os
os.environ["OMP_NUM_THREADS"] = "4"
```

**Comment by AparnaAgrawal02** [comment]
hi thanks for your time.
I set those parameters and tested on cpu and gpu :  I kept num beam as 1 and set max_len/ax_decoding_length =5 
1. For Flan-T5 large: orignal (12 CPUs) :

    seq_len: 8 time: 0.4637493824958801  
    seq_len: 32 time: 0.4152503275871277  
    seq_len: 128 time: 0.41513345956802367  
    seq_len: 512 time: 0.4186572504043579  
    seq_len: 1024 time: 0.4186951422691345  

2 . For Flan-T5 large: original (GPU)

    seq_len:  8 time:  0.10314885377883912
    seq_len: 32 time: 0.10179906606674194
    seq_len: 128 time: 0.11348598957061767
    seq_len: 512 time: 0.17275093793869017
    seq_len: 1024 time: 0.29372969150543216
1. C2 translate(12 cpus) -> 5

    seq_len: 8 time: 0.4590617847442627  
    seq_len: 32 time: 0.4289630079269409
     seq_len: 128 time:0.6012817811965943
    seq_len: 512 time:1.384908185005188

2. Ctranslate2(gpu)  

    seq_len: 8 time:  0.042198596000671384 
    seq_len: 32 time: 0.044256911277771
    seq_len: 128 time: 0.06652774572372437
    seq_len: 512 time: 0.15909862756729126 

Got very good results on GPU  but not on CPU.
I see new optimization is merged to main, is there any dev installation, or i have to clone and manually setup?

**Comment by guillaumekln** [comment]
Your results for 1. seem incorrect since the input length should make a difference in the execution time.

I also found that Transformers includes the decoder start token in `max_length`, which is not the case for CTranslate2. So `max_decoding_length` should be decreased by 1 in this comparison.

Here's the code I tested on my side:

```python
import os
os.environ["OMP_NUM_THREADS"] = "6"

import time
import ctranslate2
from transformers import T5Tokenizer, T5ForConditionalGeneration

samples = 10
batch_size = 1
seq_len = [8, 32, 128, 512]

tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-large")

converter = ctranslate2.converters.TransformersConverter("google/flan-t5-large")
model_dir = converter.convert("/tmp/ct2", force=True)
translator = ctranslate2.Translator(model_dir, device="cpu")

for i in range(4):
    start = time.time()
    for j in range(samples):
        input_text = "translate English to German: " + "house "* seq_len[i]
        input_tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(input_text))
        input_tokens = [input_tokens] * batch_size
        results = translator.translate_batch(
            input_tokens,
            beam_size=1,
            min_decoding_length=0,
            max_decoding_length=4,
        )
        output_tokens = results[0].hypotheses[0]
        output_text = tokenizer.decode(tokenizer.convert_tokens_to_ids(output_tokens))
    end = time.time()
    print("seq_len: ", seq_len[i], "time: ", (end-start)/samples)


model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-large")
model.cpu()
model.eval()

for i in range(4):
    start = time.time()
    for j in range(samples):
        input_text = "translate English to German: " + "house "* seq_len[i]
        input_text = [input_text] * batch_size
        input_ids = tokenizer(input_text, return_tensors="pt").input_ids
        outputs = model.generate(input_ids, max_length=5)
        results = tokenizer.decode(outputs[0])
    end = time.time()
    print("seq_len: ", seq_len[i], "time: ", (end-start)/samples)
```

And here are the results (with the new optimization that was referenced above even though it does not make a big difference):

* CTranslate2 (batch_size = 1)
seq_len:  8 time:  0.4341254234313965
seq_len:  32 time:  0.4234492301940918
seq_len:  128 time:  0.57331383228302
seq_len:  512 time:  1.3473652124404907

* CTranslate2 (batch_size = 8)
seq_len:  8 time:  0.5608107566833496
seq_len:  32 time:  0.8418504953384399
seq_len:  128 time:  2.7281113147735594
seq_len:  512 time:  11.134512662887573

* Transformers (batch_size = 1)
seq_len:  8 time:  0.3913001537322998
seq_len:  32 time:  0.40816874504089357
seq_len:  128 time:  0.6014061212539673
seq_len:  512 time:  1.661046576499939

* Transformers (batch_size = 8)
seq_len:  8 time:  0.6707111120223999
seq_len:  32 time:  1.1336565732955932
seq_len:  128 time:  3.203359603881836
seq_len:  512 time:  13.086178636550903

So CTranslate2 is only slightly slower on short inputs with batch_size=1. It is faster in the other cases.

**Comment by AparnaAgrawal02** [comment]
Yeah! Right. My variable was set wrong for the input in the transformer's cpu case. Sorry for the inconvenience. Thanks for your time!
