### ISSUE TITLE
pip install ctranslate2: no package found on macOS

### ISSUE THREAD

**Issue by miikargh** [OpenNMT/CTranslate2#133]
Hi, 

Running `pip install ctranslate2` with the latest pip as per the installation instructions results in the following:
```
ERROR: Could not find a version that satisfies the requirement ctranslate2== (from versions: none)
ERROR: No matching distribution found for ctranslate2==
```

```
> pip --version
pip 20.0.2 from [...]/lib/python3.8/site-packages/pip (python 3.8)
```

```
> conda --version
conda 4.7.12
```

This is on macOS Mojave 10.14.6 (18G2022)

**Comment by guillaumekln** [comment]
Hi,

Unfortunately we don't build package for macOS at the moment. The current recommendation would be to use a Docker image.

We can consider this issue for future improvement.

**Comment by miikargh** [comment]
Ok. Thanks for the info!

**Comment by guillaumekln** [comment]
macOS support was recently added to the Tokenizer thanks to @keichi: https://github.com/OpenNMT/Tokenizer/commit/9473db8b485abd947bc25936f3e4aff26e729229

Since CTranslate2 is using a similar setup, this commit can be used as an example if anyone wants to contribute. Note that a macOS wheel will most likely be CPU-only.

**Comment by keichi** [comment]
I've started working on this one. Please see #363.
