### ISSUE TITLE
How to use whisper inference using C++

### ISSUE THREAD

**Issue by endink** [OpenNMT/CTranslate2#1419]
Is this library designed primarily for python?

Compared to whipser.cpp it has better performance, but the lack of C++ examples makes it python-specific, and is there plan to add "FeatureExtractor" like faster whisper for  C++. This is not an easy task for people who are not familiar with the Mel spectrum, such as me.

**Comment by maiquanshen** [comment]
Does the whisper support batch inference？
set num_workers = 5 ，the concurrent processing does not seem to have any effect, is the function not implemented？

**Comment by guillaumekln** [comment]
CTranslate2 only implements the Whisper model and decoding. The audio processing and transcription loop is not in the scope of this repository. These steps are easier to implement in Python that's why faster-whisper is in Python.

For a full C++ execution, you would "just" need to port each line of faster-whisper to C++. Alternately you can try to fork whisper.cpp and replace the model execution by a call to CTranslate2.

**Comment by endink** [comment]
OKay, thanks for your reply.   
 This issue can be close now. It seems that extracting audio code from whisper.cpp is the fastest way to implement it.
 
 Thanks again.
