### ISSUE TITLE
Use generator as translator?

### ISSUE THREAD

**Issue by Weroxig** [OpenNMT/CTranslate2#1667]
Is it possible to use ctranslate's Generator class the same way as the Translator? For example, maybe I could form the Generator's initial prompt in some way to match the same thing that the Translator uses?

**Comment by minhthuc2502** [comment]
Opened in #1665

**Comment by Weroxig** [comment]
I think my question was too broad, for my case, I have this working:
```python
import ctranslate2
import sentencepiece as spm
translator = ctranslate2.Translator("../models/sugoi-v4-ja-en-ct2", device="cuda")
spsource = spm.SentencePieceProcessor("../models/sugoi-v4-ja-en-ct2/spm.ja.nopretok.model")
sptarget = spm.SentencePieceProcessor("../models/sugoi-v4-ja-en-ct2/spm.en.nopretok.model")
input_text = "日本語上手"
input_tokens = spsource.encode(input_text, out_type=str)
results = translator.translate_batch([input_tokens])
detokenized=""
for i in range(len(results)):
    detokenized+=sptarget.decode(results[i].hypotheses[0])
print(detokenized)
```
But I want to know if it's possible to do this with ctranslate2.Generator instead

**Comment by minhthuc2502** [comment]
Sorry for the misunderstanding. I am not sure I can understand your purpose. As I understand, you want to run a Generator to do a translation as Translator? Actually, we don't support the model like that. The backends of Generator and Translator are the same but the architecture behind in Translator is Encoder-Decoder, otherwise the architecture behind Generator is Decoder only.
