### ISSUE TITLE
A question regarding Faster Whisper

### ISSUE THREAD

**Issue by MahmoudAshraf97** [OpenNMT/CTranslate2#1802]
Hello, is [Faster Whisper](https://github.com/SYSTRAN/faster-whisper) still maintained? Your colleague Nguyễn Trung Kiên who was maintaining it is inactive since late July, is there a way to reach him? or does Systran has other plans for it?

@minhthuc2502

**Comment by minhthuc2502** [comment]
Hello, due to increased focus on internal projects, he currently don't have enough time to actively maintain Faster Whisper in parallel. I will discuss with the team to ensure we can continue maintaining this project more actively moving forward. Apologies for any inconvenience this may cause, and thank you for your understanding.

**Comment by MahmoudAshraf97** [comment]
I'm willing to actively maintain it, I.m already one of the top contributors and have several open PRs that solve several problems that were approved but not merged since august.
Can we have users from the community or volunteers to help maintain the project?
I'm willing to volunteer, if that request is plausible we can discuss getting commit access to the repo

**Comment by BBC-Esq** [comment]
I second the motion for @MahmoudAshraf97 to maintain it.  Please pass the torch to him, or someone like him, but preferably him.  I'm disheartened by Systran in general and the other people who have supposedly been in charge of maintaining it.  Make this decision ASAP.  Also, why does "Systran" maintain it at all?  I thought that it was originally owned by that "@guilliaken" guy (can never remember the proper spelling)...but he passed it to "Systran" because he got a job at Apple or something.

Anyways, this is a simple decision and doesn't need "meetings about meetings" or anything like that.  Thanks, that's my two cents worth.

**Comment by BBC-Esq** [comment]
> I'm willing to actively maintain it, I.m already one of the top contributors and have several open PRs that solve several problems that were approved but not merged since august. Can we have users from the community or volunteers to help maintain the project? I'm willing to volunteer, if that request is plausible we can discuss getting commit access to the repo

I'm adding an additional comment here in direct response to @MahmoudAshraf97...do NOT just give commit access.  Transfer full maintainability.  This was done when the @guillaumekln dude transferred it to "Systran" when he became too busy, and now, apparently, Systran is too busy, so transfer the darn thing to @MahmoudAshraf97.  He's been consistent.  Also, you'll note that the @guillaumekln transferred it in a more responsible way than you guys currently are...waiting for so long and what not.

Thanks.

**Comment by hoonlight** [comment]
I agree with @BBC-Esq .

**Comment by BBC-Esq** [comment]
> I agree with @BBC-Esq.

Yep, and I'm sure if/when @MahmoudAshraf97 gets a high paying job like the @guillaumekln dude did or something and he becomes too busy he'll transfer it to the next dude/dudette who's most responsible and consistent.  Systran, you don't own this repo, it's community-owned, just FYI.  Thanks!

**Comment by asr-lord** [comment]
I agree with you guys. @MahmoudAshraf97 is doing a great job with some PR that no are merged.

**Comment by nguyendc-systran** [comment]
Apologies for the recent lack of activity; we've been focused on some high-priority internal projects. 
I've just added you @MahmoudAshraf97 as a maintainer of the project—please check your invitation. 
We hope to contribute more actively soon and will likely add other active contributors as maintainers in the future as well.

**Comment by MahmoudAshraf97** [comment]
@nguyendc-systran Please note that I still don't have access to commit or push, I can only accept other people contributions and PRs, but not my own

**Comment by BBC-Esq** [comment]
@nguyendc-systran Again please make @MahmoudAshraf97 the owner and primary maintainer of this repo.  It is community driven and "Systran's" maintenance of it has been mediocre at best.  Also, does Systran view it as some kind of intellectual property of the company's.  Again, this is a free repository and the licensing and maintenance of it should reflect the same.

**Comment by nguyendc-systran** [comment]
@MahmoudAshraf97 it's a strange behavior, can you please retry now?

**Comment by MahmoudAshraf97** [comment]
I now have the option to merge my own PRs Thanks

**Comment by nguyendc-systran** [comment]
@BBC-Esq As mentioned, our internal priorities have caused some delays, but we plan to increase activity in the coming months. We appreciate the community's patience and are eager to collaborate with contributors to keep the project moving forward.

@MahmoudAshraf97 has admin rights and can add other contributors as needed. We're open to further discussion on how we can best support the project together.

**Comment by BBC-Esq** [comment]
Thanks for your response, even if I disagree with your approach.  Does Systran view itself as owning this repository as its intellectual property or is it's involvement purely as a hobby for the betterment of the open source community.  I'm not interested in participating in and/or improving Systran's programs in support of it's company's goals.  I am, however, interested in having a good time participating in free, open-source projects with other like minded individuals.  If you could clarify Systran's role in this repo I'd appreciate it.  If you guys view faster-whisper as some kind of intellectual property that Systran owns, I'd like to know about it.  Thanks.

**Comment by vince62s** [comment]
@BBC-Esq I am not a Systran a employee but a maintainer of the OpenNMT galaxy. I would like you to remain polite with maintainers especially with Systran's employee.
If you are not happy with the cycle of maintenance of these repo, feel free to open your own Branch, invite some people to contribute and make your branch a successful project.
Systran has been contributing a LOT to the open source community with OpenNMT, Ctranslate2 and other FasterWhisper. All these projects are MIT Licensed which means that it's open to everyone and not "making Systran richer with some external PRs".
Again feel free to build your own repo.
Cheers.

**Comment by BBC-Esq** [comment]
Those are terms that accurately describe the handling of the faster-whisper repository.  But again, I'd like to believe Systran's statements that they intend in the future to take a more active role and will strive to give them the benefit of the doubt in that regard as well.  In the scant participating they've done since taking over the repo everything they've done has been good so.  And this is a great repository, and it is free like you say, and I am glad that @MahmoudAshraf97 has been finally given some leeway to address the issue...time will tell.

I hope that I'm not banned like you say and I'd like to continue to participate.  Thanks.

**Comment by nguyendc-systran** [comment]
@BBC-Esq, I’d like to clarify that this project was originally created by Guillaume while he was employed at Systran, which is why it was transferred to us when he left. Since then, our team, including @minhthuc2502 and @trungkienbkhn, has continued to maintain these projects. While recent activity has slowed due to internal priorities, this doesn’t mean the project is abandoned.

We appreciate the community’s contributions and understand the desire for more regular activity, but I do want to respectfully address that terms like "mediocre", "negligent" and "scant participating" don’t reflect the efforts that have been put into maintaining the project over the time. We’re committed to the project and open to collaborating more with active contributors to keep it moving forward, including adding maintainers where needed.

Everyone is, of course, free to contribute or not, but I would encourage us all to keep discussions constructive so we can continue improving the project together.

**Comment by BBC-Esq** [comment]
Ok, the fact that your responded the way you did alleviates some of my concerns and I apologize for the somewhat "inflammatory" language.  I'm okay with continuing to contribute and participate moving forward.  Let me know if I can help!  I'm still working on the benchmarking stuff with @MahmoudAshraf97 but it's been kind of on the backburner due to other obligations...Thanks!
