### ISSUE TITLE
latency drop a lot with large beam size 

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/CTranslate2#264]
I was trying to serve a transformer model, found that latency drops a lot when in beam 15. (my scenario need big beam, like 30)

Beam size | Latency @95 (ms)
-- | --
5 | 19.7
10 | 22
15 | 87
20 | 114
30 | 160

1. My GPU is V100, any insight of the root cause? 
2. if need profiling, I am new to profiling, suggestion where to start?

really appreciate your help, below is my model setting.

```
vocabulary size: 100000
decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
enc_layers: 6
dec_layers: 3
transformer_ff: 1024
heads: 8
```

**Comment by WangYongzhao** [comment]
oh, I just found that with this fix(https://github.com/OpenNMT/CTranslate2/pull/263), drop issue is solved now.

**Comment by guillaumekln** [comment]
Can you also try with smaller batch sizes?

I think the issue comes from the [caching allocator configuration](https://github.com/OpenNMT/CTranslate2/blob/master/docs/performance.md#cuda-caching-allocator). The default values are mostly tuned for a small beam size (<= 5). You could look into changing the configuration but it's a bit difficult to get it right.

**Comment by WangYongzhao** [comment]
thanks, my batch size is 1.
I will take a see on the caching.

**Comment by WangYongzhao** [comment]
I found that increase the max_cached_bytes could alleviate the latency drop issue with large beam size, thanks for your help. @guillaumekln
