### ISSUE TITLE
Batch Type

### ISSUE THREAD

**Issue by Sujit27** [OpenNMT/CTranslate2#357]
I understand that setting a max_batch_size sorts the input of sentences and chunks it into batches according to the max_batch_size provided, thus reducing sentence padding and improving performance. How does setting the batch type as "tokens" make the total number of elements in batch more constant ? How does this help performance ?

**Comment by guillaumekln** [comment]
The encoder input has shape `[num_examples, max_length]`. The batch type defines how `num_examples` is set. With batch type "tokens", we set `num_examples` so that the number of elements `num_examples * max_length` is equal to `max_batch_size`. So the number of elements is constant for any values of `max_length`.

This can help for performance especially on GPU where we use a caching allocator. If tensor sizes do not change much, we can reuse memory that was previously allocated and skip a costly allocation.

**Comment by Sujit27** [comment]
Thank you.
