### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by euberdeveloper** [OpenNMT/CTranslate2#518]
I tried to make a Dockerfile with python3.8-alpine, that used ctranslate2 as dependency, but I can't make it to be installed. Do you support Alpine OS?

**Comment by guillaumekln** [comment]
Can you post the content of your Dockerfile?

**Comment by euberdeveloper** [comment]
I am trying to make this Dockerfile work on Alpine, in order to save some disk space https://github.com/LibreTranslate/LibreTranslate/blob/main/Dockerfile

The only difference is that I changed the python to -alpine and that I added the icu-dev package because eit was not included with alpine (apk add icu-dev)

**Comment by guillaumekln** [comment]
After a quick research, I confirm that the published Python wheels do not support Alpine. The wheels require a glibc-based Linux system, but Alpine does not use glibc.

There is no plan to publish something specific to Alpine. The current workaround would be to recompile the Python wheels on Alpine.

**Comment by caseyng** [comment]
For anyone landing here: I've published a working Alpine-based Docker image that builds CTranslate2 from source on musl/aarch64 and amd64.

**ghcr.io/caseyng/faster-whisper-alpine** — https://github.com/caseyng/faster-whisper-alpine

Five compatibility issues had to be solved beyond just "recompile on Alpine":
1. **musl `stat64`/`fstat64` missing** — spdlog uses glibc-only symbols; fixed with `-Dfstat64=fstat -Dstat64=stat`
2. **PyAV + FFmpeg 8.x** — Alpine 3.23 ships FFmpeg 8 which removed `AVFMT_ALLOW_FLUSH`; `av>=13` required
3. **CMake 4.x policy** — some submodules declare `cmake_minimum_required < 3.5`, rejected by CMake 4; fixed with `-DCMAKE_POLICY_VERSION_MINIMUM=3.5`
4. **cxxopts missing `<cstdint>`** — CLI tool fails with GCC 14; fixed with `-DBUILD_CLI=OFF`
5. **ARM64 int8** — needs `-march=armv8-a+dotprod` at compile time

**Comment by AlexxIT** [comment]
Thanks, @caseyng. I also built Python wheels for `amd64` and `arm64` based on his work https://github.com/AlexxIT/ctranslate2-alpine

**Comment by jordimas** [comment]
> Thanks, [@caseyng](https://github.com/caseyng). I also built Python wheels for `amd64` and `arm64` based on his work https://github.com/AlexxIT/ctranslate2-alpine

Hello. I would like to publish a generic CTranslate2 image (no faster whisper) here:
https://github.com/OpenNMT/CTranslate2/pkgs/container/ctranslate2

Would be interested in doing a PR and contribute this?
Thanks

**Comment by AlexxIT** [comment]
@jordimas I don't understand your question. Containers build on Ubuntu. There are no problems with them.
