### ISSUE TITLE
Support speech-to-text Transformer model

### ISSUE THREAD

**Issue by gfiameni** [OpenNMT/CTranslate2#578]
Hi! I would like to use `ct2-fairseq-converter` to translate an existing fairseq trained model. However, since the converter supports a limited set of architectures, wondering what the best approach to add a new model would be.

Thanks!

**Comment by guillaumekln** [comment]
Hi,

What custom model architecture are you referring to? Can you post the Fairseq options that are used?

If the model architecture is close to a standard Transformer, we may be able to support it and treat this issue as a feature request. Otherwise, you would need to implement the architecture in the code which may be non trivial as it requires experience with C++.

**Comment by NeonBohdan** [comment]
Implementing [wav2vec 2.0](https://github.com/facebookresearch/fairseq/tree/main/examples/wav2vec#wav2vec-20) will be very useful 

I think CTranslate2 is the best CPU Transformer inference accelerator
If it will manage to get the same great performance improvement for wav2vec 2.0 it will become insane
After addition of some [transformers](https://github.com/huggingface/transformers) it already became the best

**Comment by guillaumekln** [comment]
I'm closing this issue that I turned into a generic issue for speech-to-text. Feel free to open a new issue if you want to see support for another model architecture.

**Comment by ryanheise** [comment]
FYI, there is a new issue for wav2vec 2.0 here: #1361 .

I think that the work done for Whisper may have helped to lay some of the groundwork for this, since both Whisper and wav2vec2 begin with convolutional layers to process the audio input, and of course they both use transformers downstream, albeit differently.
