### ISSUE TITLE
Marian-converter support pre-norm?

### ISSUE THREAD

**Issue by McVilla** [OpenNMT/CTranslate2#805]
When I use ct2-marian-converter marian pre-norm model, the set_layer_norm function seems not match the key (encoder_l9_ffn_ffn_ln_scale_pre). Can I just simply change the string?

**Comment by guillaumekln** [comment]
The converter is supposed to support pre-norm models, but I did not realise layer norm weights have a suffix in this case ("_pre").

Do you want to send a PR with the fix? We could just update `set_layer_norm` to use the weights with the "_pre" suffix if they exist, otherwise it uses the weights without the suffix.
