### ISSUE TITLE
Released model structural change in 2.19.1 ?

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/CTranslate2#909]
Hello @guillaumekln ,

We just noticed a potentially unwanted behavior. A model converted from an OpenNMT-py checkpoint with recent releases (from 2.19.1) is unstable (repeating first token until max_decoding_length) when inferring with 2.16.0.
This is probably not a main concern, as we should indeed infer with a version >= to the version we released with, but I prefer to document this in case there might be any underlying bug somewhere.

Does this ring a bell?

**Comment by guillaumekln** [comment]
Hi,

Forward compatibility is not supported as per the [documentation](https://opennmt.net/CTranslate2/conversion.html#backward-compatibility). In general we still try to show an explicit error when forward compatibility is broken, but it's not systematic because it is not always obvious that a change broke it.

I think the issue happened when we removed an attribute related the embeddings scaling that was no longer used:

* https://github.com/OpenNMT/CTranslate2/commit/5ee3717020ce10fe4f388f3b18a20582501d5465
* https://github.com/OpenNMT/CTranslate2/commit/2c8db5e48256f17cbd1413ba6b287d6aaa4b25e3

We should have increased a revision number when making this change.
